# Generated by Django 5.0.1 on 2024-02-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iadsapp', '0002_awards_gamenews_upcomingreleases'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Awards',
            new_name='Award',
        ),
        migrations.RenameModel(
            old_name='GameDetails',
            new_name='GameDetail',
        ),
        migrations.RenameModel(
            old_name='GameNews',
            new_name='GameNew',
        ),
        migrations.RenameModel(
            old_name='UpcomingReleases',
            new_name='UpcomingRelease',
        ),
    ]
