# Generated by Django 5.0.2 on 2024-03-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iadsapp', '0003_rename_awards_award_rename_gamedetails_gamedetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gamedetail',
            options={'ordering': ['game_type']},
        ),
        migrations.RemoveField(
            model_name='gamenew',
            name='link',
        ),
    ]
