# Generated by Django 5.0.2 on 2024-03-11 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iadsapp', '0004_userprofile_alter_gamedetail_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='link',
        ),
        migrations.AddField(
            model_name='award',
            name='award_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='award',
            name='award_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='award',
            name='award_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
