# Generated by Django 5.0.2 on 2024-03-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iadsapp', '0005_remove_award_link_award_award_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='game_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
