# Generated by Django 4.2.10 on 2024-03-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iadsapp', '0007_calendarevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='LastName',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='FirstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='award',
            name='game_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
