# Generated by Django 5.0.2 on 2024-03-16 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iadsapp', '0008_rename_username_userprofile_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, max_length=3000)),
                ('rate', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Unplayable'), (2, '2 - Awful'), (3, '3 - Poor'), (4, '4 - Mediocre'), (5, '5 - Average'), (6, '6 - Decent'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Excellent'), (10, '10 - Outstanding')])),
                ('likes', models.PositiveIntegerField(default=0)),
                ('unlikes', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iadsapp.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iadsapp.userprofile')),
            ],
        ),
    ]
