# Generated by Django 5.0.1 on 2024-03-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iadsapp', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
