# Generated by Django 5.0.2 on 2024-03-20 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iadsapp', '0012_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetail',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='ratings',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Unplayable'), (2, '2 - Awful'), (3, '3 - Poor'), (4, '4 - Mediocre'), (5, '5 - Average'), (6, '6 - Decent'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Excellent'), (10, '10 - Outstanding')], null=True),
        ),
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iadsapp.gamedetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Unplayable'), (2, '2 - Awful'), (3, '3 - Poor'), (4, '4 - Mediocre'), (5, '5 - Average'), (6, '6 - Decent'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Excellent'), (10, '10 - Outstanding')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iadsapp.gamedetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
